# Generated by Django 3.2 on 2021-04-14 13:40

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('owner_name', models.CharField(max_length=100)),
                ('rating', models.PositiveIntegerField(default=0)),
                ('address', models.TextField()),
                ('number_of_rooms', models.PositiveSmallIntegerField(default=1)),
                ('area', models.DecimalField(decimal_places=1, max_digits=4)),
                ('furnuture', models.BooleanField(default=False)),
                ('city', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
    ]
