# Generated by Django 3.1.7 on 2021-04-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0002_auto_20210416_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='estate_type',
            field=models.CharField(choices=[('appartment', 'квартира'), ('house', 'частный дом'), ('industry', 'производственное помещение'), ('warehouse', 'складское помещение')], default='appartment', max_length=10),
        ),
        migrations.AddField(
            model_name='realestate',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
